import type { Email, Task } from "@/types";

export const mockEmails: Email[] = [
  {
    id: "1",
    from: "manager@company.com",
    subject: "Urgent: Q4 Review Meeting",
    body: "We need to discuss the Q4 review tomorrow at 2 PM. Please prepare your presentation.",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
    priority: 0.95,
    senderImportance: 0.9,
    projectRelevance: 0.8,
    deadlineProximity: 0.9,
    urgency: 0.95,
    folder: "inbox",
  },
  {
    id: "2",
    from: "client@external.com",
    subject: "Project Proposal Feedback",
    body: "Thank you for the proposal. We have some feedback and questions.",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    read: false,
    priority: 0.75,
    senderImportance: 0.8,
    projectRelevance: 0.9,
    deadlineProximity: 0.6,
    urgency: 0.7,
    folder: "inbox",
  },
  {
    id: "3",
    from: "team@company.com",
    subject: "Weekly Standup Notes",
    body: "Here are the notes from today's standup meeting.",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: true,
    priority: 0.3,
    senderImportance: 0.5,
    projectRelevance: 0.6,
    deadlineProximity: 0.2,
    urgency: 0.3,
    folder: "inbox",
  },
  {
    id: "4",
    from: "hr@company.com",
    subject: "Benefits Open Enrollment",
    body: "Open enrollment for benefits starts next week. Please review your options.",
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    read: false,
    priority: 0.5,
    senderImportance: 0.6,
    projectRelevance: 0.3,
    deadlineProximity: 0.4,
    urgency: 0.5,
    folder: "inbox",
  },
  {
    id: "5",
    from: "support@service.com",
    subject: "Your subscription will renew soon",
    body: "Your subscription to our service will automatically renew in 7 days.",
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    read: false,
    priority: 0.2,
    senderImportance: 0.3,
    projectRelevance: 0.2,
    deadlineProximity: 0.3,
    urgency: 0.2,
    folder: "inbox",
  },
  {
    id: "6",
    from: "colleague@company.com",
    subject: "Question about API documentation",
    body: "Could you help me understand the authentication flow in the API docs?",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    read: false,
    priority: 0.4,
    senderImportance: 0.4,
    projectRelevance: 0.5,
    deadlineProximity: 0.1,
    urgency: 0.4,
    folder: "inbox",
  },
  {
    id: "7",
    from: "ceo@company.com",
    subject: "All-hands meeting announcement",
    body: "We'll have an all-hands meeting this Friday at 3 PM to discuss company updates.",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    read: false,
    priority: 0.6,
    senderImportance: 1.0,
    projectRelevance: 0.4,
    deadlineProximity: 0.5,
    urgency: 0.6,
    folder: "inbox",
  },
  {
    id: "8",
    from: "system@company.com",
    subject: "Password reset requested",
    body: "You recently requested a password reset. If this wasn't you, please contact IT.",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    read: true,
    priority: 0.1,
    senderImportance: 0.2,
    projectRelevance: 0.1,
    deadlineProximity: 0.1,
    urgency: 0.1,
    folder: "inbox",
  },
];

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Create website analytics dashboard",
    description:
      "Build a comprehensive analytics dashboard with charts and metrics",
    status: "in-progress",
    priority: "P1",
    dueDate: new Date(Date.now()),
    source: "external",
    project: "Design Revisions",
    assignee: "Current User",
  },
  {
    id: "2",
    title: "Edit existing button",
    description: "Update the button styling and behavior",
    status: "in-progress",
    priority: "P2",
    dueDate: new Date(Date.now()),
    source: "external",
    project: "Design Revisions",
    assignee: "Current User",
  },
  {
    id: "3",
    title: "Remove button",
    description: "Remove deprecated button component",
    status: "ready",
    priority: "P2",
    dueDate: new Date(Date.now()),
    source: "external",
    project: "Product roadmap",
    assignee: "Current User",
  },
  {
    id: "4",
    title: "Remove deprecated button",
    description: "Clean up old button implementation",
    status: "ready",
    priority: "P3",
    dueDate: new Date(Date.now()),
    source: "external",
    project: "User review",
    assignee: "Current User",
  },
  {
    id: "5",
    title: "Add new button",
    description: "Create new button component with updated design",
    status: "backlog",
    priority: "P3",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    source: "external",
    project: "Product roadmap",
    assignee: "Current User",
  },
  {
    id: "6",
    title: "Edit button",
    description: "Modify button component properties",
    status: "ready",
    priority: "P2",
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    source: "external",
    project: "Design Revisions",
    assignee: "Current User",
  },
  {
    id: "7",
    title: "Duplicate button",
    description: "Create duplicate of existing button",
    status: "ready",
    priority: "P2",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    source: "external",
    project: "Product roadmap",
    assignee: "Current User",
  },
  {
    id: "8",
    title: "Share button",
    description: "Implement share functionality button",
    status: "ready",
    priority: "P3",
    dueDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
    source: "external",
    project: "Product roadmap",
    assignee: "Current User",
  },
  {
    id: "9",
    title: "Add new button",
    description: "Create additional button variant",
    status: "review",
    priority: "P3",
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    source: "external",
    project: "User review",
    assignee: "Current User",
  },
  {
    id: "10",
    title: "Create website analytics dashboard",
    description: "Build analytics dashboard",
    status: "review",
    priority: "P1",
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    source: "external",
    project: "Design Revisions",
    assignee: "Current User",
  },
  {
    id: "11",
    title: "Add new button",
    description: "New button implementation",
    status: "done",
    priority: "P3",
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    source: "external",
    project: "Product roadmap",
    assignee: "Current User",
  },
  {
    id: "12",
    title: "Create website analytics dashboard",
    description: "Analytics dashboard v1",
    status: "done",
    priority: "P1",
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    source: "external",
    project: "Product roadmap",
    assignee: "Current User",
  },
];
